### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-css-stealing-styles-xedvDK#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://kisyular.github.io/MI-449-SS17-740-css-stealing-styles-xedvDK/) and meets the following criteria:

- [x] The page includes the name of your search engine in big letters (you can make it up), with a search `input` below it, then a button below that to run the search (the button doesn't have to do anything for this prototype)
- [x] The font size of the search engine name is at least 70 pixels, so that it's very easy to see
- [x] `span` elements are wrapped around each letter of the name, like this: `<span>G</span><span>o</span><span>o</span><span>g</span><span>l</span><span>e</span>`, so that they can be styled individually with classes
- [x] The on-hover colors from the paragraphs [on this page](http://skillful-clouds.surge.sh/) are used to color individual letters of your name (similar to the letters in Google's logo)
- [x] Inspect the `input` element at the bottom of the [_Prototyping states_ page of the lesson](5) to create an identical-looking search box for your own site (it should even use the same styles on `focus`)
- [x] The styles from the "Create Account" button [on this page](http://plant-servant.surge.sh/) are used for your "Search" button (it should even use the same styles on `hover` and `active`)
- [x] There are no stylelint errors in your CSS (this will also be expected for all future projects)
- [x] All your CSS exists in a `.css` file

**Comment by KatieMFritz** [comment]
Hi Rellikson! 🌴 🐱 🎈 

This is a strong start, but it's not quite meeting the criteria yet. 

### Use exact colors 

> The on-hover colors from the paragraphs [on this page](http://skillful-clouds.surge.sh/) are used to color individual letters of your name (similar to the letters in Google's logo)

Looks like you currently have your letters styled with different colors that appear on `:hover`,  but we're looking for the colors to _always_ be there. And instead of using basic HTML colors like `red` and `green`, we want you to use the _exact_ colors used on that page when you hover over the words - you'll have to use some fancy Inspect skills to get them! :art: 
* * *
### Replicate the `input` element from the lesson 

> Inspect the `input` element at the bottom of the [Prototyping states page of the lesson](https://msu.lansing.codes/courses/MI-000-SS00-000/lessons/css-stealing-styles/5) to create an identical-looking search box for your own site (it should even use the same styles on `focus`)

Like the example `input`, yours has rounded corners and turns green on `focus`. However, the example uses a specific shade of green, and the text when you type is much smaller. Take another look and see if you can get them to be closer.

:bulb: Tip: If you don't want the `input` to be as wide as the entire screen, try giving your `div.centerForm` a max-width (somewhere between 600px and 1000px would be good) and setting `margin: 0 auto` (this centers it on the page). 
* * *
### Exactly replicate button 

> The styles from the "Create Account" button [on this page](http://plant-servant.surge.sh/) are used for your "Search" button (it should even use the same styles on `hover` and `active`)

Your button is close, but not quite the same. Two things I notice immediately are that there's more of a border or shadow around your button, and nothing happens stylistically when I hover over it. The `active` state seems different as well. 

One thing that tripped me up, when I tested this project, is that the source button (on the Stripe page) is not actually a `button` element. Instead, it's `a` nested in `li` nested in `ul`. Different browser styles get applied to different elements (and Bootstrap compounds that - see below). It's _possible_ to make the button exactly the same using a `button` element, but it might be easier if you use similar markup to the example. 
* * *
### HTML must be valid

I ran your code through the [W3 Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fkisyular.github.io%2FMI-449-SS17-740-css-stealing-styles-xedvDK%2F) and got an error. If you'd like, you can bypass the error by simplifying your HTML. Since this is just a prototype, it's okay if you're not using form labels and other completely semantic code.

However you decide to approach it, please make sure your page returns no errors before resubmitting. 👍 
* * *
### :bulb: Tip: Don't use Bootstrap for this project

It's not _wrong_ to use Bootstrap for this, but for this project, it's actually making things harder for you! 😬 Bootstrap applies a lot of styles to elements, even when you don't use Bootstrap's special classes. Instead of just _adding_ styles that you want, you have to worry about finding and _removing_ (overriding) styles that you _don't_ want. Does that make sense?

For this project, I recommend writing all your own CSS, or using `normalize.css` to give you a nice clean slate. 

* * *
I know that's a lot of changes! This project is intentionally tricky. It's supposed to make you practice using the Inspect tools in Chrome and think carefully about your code, because those are very useful developer skills. If you get stuck on anything, I'd be happy to work with you over video or Slack. 😄 

Otherwise, after you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by kisyular** [comment]
@KatieMFritz I have update the project based on your insights above. I have changed the input and the button (li tag) to match with those of the suggested website.

However, I am really having trouble with the input. I can get to fix the font-size to match with the reference input.

**Comment by KatieMFritz** [comment]
It's getting closer! ⭐️ I'd be happy to work with you on this. I think it would be easiest to do a call with screen sharing, or even meet in person. I sent you a message on Slack to set something up. 😁

**Comment by kisyular** [comment]
@KatieMFritz, Thank you for the help. I fixed the Font-Colors and Font-size. I also ran my index.html through  W3 Validator and showed no error. Kindly take a look and lemme me know.

Thank you

**Comment by KatieMFritz** [comment]
Nice job fixing stuff! The input looks better and the colors are exactly what we are looking for.

:shipit:
